# docker-Specify the compose version
version: "3"

services:
  app:
    #Build a Dockerfile in the same directory
    build: .
    #You can keep the container running.
    tty: true
    #Mount the files in the directory to the app directory in the container
    volumes: 
      - ./dist:/app/dist
      - ./src:/app/src
      - ./img:/app/img
      - ./webpack:/app/webpack
      - ./service-worker.js:/app/service-worker.js
    #Mount port 1000 on the container side to port 8080 on the host side.
    #ports:
    #  - "8080:8080"